steps:
  - uses: actions/checkout@v2

  - name: Auto Minify
    uses: nizarmah/auto-minify@v2
    with:
      maxdepth: 1

  - name: Auto commit minified files
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: "Auto Minification"
