name: Minify CSS
on:
  push:
    branches:
      - main
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          maxdepth: 2
      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Minification
          commit_user_name: Pratyush Nalam
          commit_user_email: code@pratyushnalam.com
          commit_author: Pratyush Nalam <code@pratyushnalam.com>
