name: Minify CSS
on:
  push:
    branches:
      - main
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1.1
        with:
          maxdepth: 2
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: Auto Minification
          commit_user_name: Pratyush Nalam
          commit_user_email: code@pratyushnalam.com
          commit_author: Pratyush Nalam <code@pratyushnalam.com>
